name: C# API CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore AdvocaciaDigital.Api.csproj

    - name: Build
      run: dotnet build AdvocaciaDigital.Api.csproj --no-restore

    - name: Run tests # Adicione seus comandos de teste aqui, se tiver
      run: echo "No tests defined yet for C# API."
      # run: dotnet test AdvocaciaDigital.Api/AdvocaciaDigital.Api.csproj --no-build